apiVersion: v1
kind: Pod
metadata:
  labels:
    app: bernard-nginx
  name: bernard-nginx
spec:
  containers:
  - name: bernard-nginx
    image: nginx:latest
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 10
    env:
    - name: DB_CONNECT
      valueFrom:
        configMapKeyRef:
          name: bernard-env
          key: DB_URL
